"use client";

import { useState } from "react";
import ATSScoreRing from "./ATSScoreRing";

export interface InterviewEvaluationResult {
  overall_score: number;
  score_explanation: string;
  communication_score: number;
  technical_score: number;
  confidence_score: number;
  strengths: string[];
  areas_to_improve: string[];
  detailed_qa_feedback?: Array<{
    question: string;
    user_answer: string;
    feedback: string;
    suggested_answer: string;
  }>;
}

interface InterviewResultsViewProps {
  result: InterviewEvaluationResult;
  onRestartSession: () => void;
  jobRole?: string;
}

export default function InterviewResultsView({
  result,
  onRestartSession,
  jobRole,
}: InterviewResultsViewProps) {
  const [expandedQA, setExpandedQA] = useState<number | null>(null);

  const springTransition = "transform 0.18s cubic-bezier(0.34, 1.56, 0.64, 1)";
  const springBtn = {
    onMouseEnter: (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(1.04)"; },
    onMouseLeave: (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(1)"; },
    onMouseDown:  (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(0.97)"; },
    onMouseUp:    (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(1.04)"; },
  };

  const downloadReport = () => {
    const lines = [
      "AI MOCK INTERVIEW PERFORMANCE REPORT",
      "Generated by Resumé Edge",
      "=".repeat(55),
      "",
      `TARGET ROLE: ${jobRole ? jobRole.toUpperCase() : "GENERAL SOFTWARE EVALUATION"}`,
      `OVERALL INTERVIEW SCORE: ${result.overall_score}/100`,
      result.score_explanation,
      "",
      "CATEGORY BREAKDOWN",
      "-".repeat(35),
      `- Communication & Clarity: ${result.communication_score}/100`,
      `- Technical & Domain Knowledge: ${result.technical_score}/100`,
      `- Response Structure & Confidence: ${result.confidence_score}/100`,
      "",
      "AREAS WHERE YOU ARE GOOD (STRENGTHS)",
      "-".repeat(35),
      ...result.strengths.map((s, i) => `[✓] ${s}`),
      "",
      "AREAS TO IMPROVE",
      "-".repeat(35),
      ...result.areas_to_improve.map((a, i) => `[↑] ${a}`),
      "",
    ];

    if (result.detailed_qa_feedback && result.detailed_qa_feedback.length > 0) {
      lines.push("QUESTION-BY-QUESTION FEEDBACK & SUGGESTED REWRITES");
      lines.push("=".repeat(55));
      result.detailed_qa_feedback.forEach((qa, idx) => {
        lines.push(`\n[Q${idx + 1}] ${qa.question}`);
        lines.push(`Candidate Answer: ${qa.user_answer}`);
        lines.push(`Feedback: ${qa.feedback}`);
        lines.push(`Suggested High-Impact Answer:\n  ${qa.suggested_answer}`);
      });
    }

    const text = lines.join("\n");
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "AI_Interview_Performance_Report.txt";
    a.click();
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header Title */}
      <div className="text-center mb-8">
        <h2 style={{ fontFamily: "var(--font-display)", fontSize: "2rem", fontWeight: 700, color: "var(--ink)" }}>
          Interview Performance Report
        </h2>
        <p className="text-sm mt-1" style={{ color: "var(--muted)" }}>
          Detailed AI analysis of your communication, technical answers, and key areas for growth.
        </p>
      </div>

      {/* 2-Column Grid Layout */}
      <div className="grid md:grid-cols-3 gap-6">
        {/* Left Column (1/3 width) - Overall Rating & Categories */}
        <div className="space-y-5">
          {/* Rating Ring Card */}
          <div
            className="p-6 text-center animate-scale-in"
            style={{
              background: "var(--paper)",
              border: "1px solid var(--border)",
              borderRadius: "1.5rem",
              boxShadow: "0 4px 20px rgba(0,0,0,0.1)",
            }}
          >
            <p className="text-xs font-semibold uppercase tracking-widest mb-4" style={{ color: "var(--muted)" }}>
              Overall Interview Rating
            </p>
            <ATSScoreRing score={result.overall_score} explanation="Interview Performance Index" />
          </div>

          {/* Category Breakdown Progress Cards */}
          <div
            className="p-6 space-y-4"
            style={{
              background: "var(--paper)",
              border: "1px solid var(--border)",
              borderRadius: "1.5rem",
              boxShadow: "0 4px 20px rgba(0,0,0,0.1)",
            }}
          >
            <p className="text-xs font-bold uppercase tracking-widest mb-3" style={{ color: "var(--ink)" }}>
              Category Breakdown
            </p>

            <div>
              <div className="flex justify-between text-xs font-semibold mb-1.5">
                <span style={{ color: "var(--ink)" }}>Communication &amp; Clarity</span>
                <span style={{ color: "var(--green)" }}>{result.communication_score}/100</span>
              </div>
              <div className="w-full h-2 rounded-full bg-gray-200 dark:bg-gray-800 overflow-hidden">
                <div className="h-full rounded-full bg-[#84cc16] transition-all duration-500" style={{ width: `${result.communication_score}%` }} />
              </div>
            </div>

            <div>
              <div className="flex justify-between text-xs font-semibold mb-1.5">
                <span style={{ color: "var(--ink)" }}>Technical &amp; Domain Knowledge</span>
                <span style={{ color: "var(--ink)" }}>{result.technical_score}/100</span>
              </div>
              <div className="w-full h-2 rounded-full bg-gray-200 dark:bg-gray-800 overflow-hidden">
                <div className="h-full rounded-full bg-[#C8F135] transition-all duration-500" style={{ width: `${result.technical_score}%` }} />
              </div>
            </div>

            <div>
              <div className="flex justify-between text-xs font-semibold mb-1.5">
                <span style={{ color: "var(--ink)" }}>Confidence &amp; Response Structure</span>
                <span style={{ color: "var(--gold)" }}>{result.confidence_score}/100</span>
              </div>
              <div className="w-full h-2 rounded-full bg-gray-200 dark:bg-gray-800 overflow-hidden">
                <div className="h-full rounded-full bg-amber-500 transition-all duration-500" style={{ width: `${result.confidence_score}%` }} />
              </div>
            </div>
          </div>
        </div>

        {/* Right Column (2/3 width) - Strengths, Improvements & Q&A Rewrites */}
        <div className="md:col-span-2 space-y-5">
          {/* Summary Card */}
          <div
            className="p-6 rounded-3xl border"
            style={{
              background: "var(--cream)",
              borderColor: "rgba(200, 241, 53, 0.4)",
            }}
          >
            <p className="text-xs font-bold uppercase tracking-widest mb-2 text-[#C8F135]">
              Executive Summary
            </p>
            <p className="text-sm leading-relaxed text-[var(--ink)]">{result.score_explanation}</p>
          </div>

          {/* Strengths Card */}
          <div
            className="p-6 rounded-3xl border"
            style={{
              background: "var(--paper)",
              borderColor: "var(--border)",
              boxShadow: "0 4px 20px rgba(0,0,0,0.1)",
            }}
          >
            <div className="flex items-center gap-2 mb-4">
              <span className="w-2.5 h-2.5 rounded-full bg-[#84cc16]" />
              <h3 className="text-xs font-bold uppercase tracking-widest" style={{ color: "var(--green)" }}>
                Areas Where You Excel (Strengths)
              </h3>
            </div>
            <ul className="space-y-2.5">
              {result.strengths.map((strength, idx) => (
                <li key={idx} className="text-sm flex items-start gap-2.5">
                  <span className="text-[#84cc16] font-bold shrink-0 mt-0.5">✓</span>
                  <span className="text-[var(--ink)] leading-relaxed">{strength}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Areas to Improve Card */}
          <div
            className="p-6 rounded-3xl border"
            style={{
              background: "var(--paper)",
              borderColor: "var(--border)",
              boxShadow: "0 4px 20px rgba(0,0,0,0.1)",
            }}
          >
            <div className="flex items-center gap-2 mb-4">
              <span className="w-2.5 h-2.5 rounded-full bg-amber-500" />
              <h3 className="text-xs font-bold uppercase tracking-widest text-amber-500">
                Key Areas to Improve
              </h3>
            </div>
            <ul className="space-y-2.5">
              {result.areas_to_improve.map((area, idx) => (
                <li key={idx} className="text-sm flex items-start gap-2.5">
                  <span className="text-amber-500 font-bold shrink-0 mt-0.5">↑</span>
                  <span className="text-[var(--ink)] leading-relaxed">{area}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Detailed Question Feedback Cards */}
          {result.detailed_qa_feedback && result.detailed_qa_feedback.length > 0 && (
            <div className="space-y-4 pt-2">
              <h3 className="text-sm font-bold uppercase tracking-widest" style={{ color: "var(--ink)" }}>
                Question Breakdown &amp; Suggested Answers
              </h3>

              {result.detailed_qa_feedback.map((qa, idx) => (
                <div
                  key={idx}
                  className="p-6 rounded-3xl border transition-all shadow-sm hover:shadow-md"
                  style={{ background: "var(--paper)", borderColor: "var(--border)" }}
                >
                  <p className="text-xs font-bold text-[var(--muted)] mb-1">Question {idx + 1}</p>
                  <h4 className="text-sm font-bold text-[var(--ink)] mb-2">{qa.question}</h4>
                  <p className="text-xs text-[var(--muted)] mb-3 leading-relaxed">
                    <strong className="text-[var(--ink)]">Your Response:</strong> {qa.user_answer}
                  </p>
                  <p className="text-xs text-amber-900 dark:text-amber-200 bg-amber-50 dark:bg-amber-950/40 p-3 rounded-xl border border-amber-200 dark:border-amber-700/50 mb-3">
                    <strong>Feedback:</strong> {qa.feedback}
                  </p>

                  <button
                    onClick={() => setExpandedQA(expandedQA === idx ? null : idx)}
                    className="text-xs font-bold text-[var(--ink)] hover:underline flex items-center gap-1 mt-2 cursor-pointer"
                  >
                    {expandedQA === idx ? "Hide Suggested Answer ↑" : "Show High-Impact Answer Rewrite →"}
                  </button>

                  {expandedQA === idx && (
                    <div className="mt-3 p-4 rounded-2xl bg-[#111927] text-white text-xs leading-relaxed animate-fade-in border border-[#C8F135]/30">
                      <span className="text-[#C8F135] font-bold block mb-1">Recommended Response:</span>
                      {qa.suggested_answer}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Bottom Action Row */}
      <div className="flex flex-col sm:flex-row gap-4 justify-center items-center pt-6">
        <button
          onClick={downloadReport}
          style={{
            background: "var(--paper)",
            border: "1px solid var(--border)",
            borderRadius: "999px",
            color: "var(--ink)",
            fontFamily: "var(--font-display)",
            fontWeight: 700,
            transition: springTransition,
          }}
          {...springBtn}
          className="px-6 py-3 text-xs font-bold shadow-sm cursor-pointer"
        >
          Download Interview Report
        </button>

        <button
          onClick={onRestartSession}
          style={{
            background: "var(--accent)",
            color: "var(--accent-dark)",
            borderRadius: "999px",
            fontFamily: "var(--font-display)",
            fontWeight: 700,
            transition: springTransition,
            boxShadow: "0 2px 12px rgba(200, 241, 53, 0.4)",
          }}
          {...springBtn}
          className="px-6 py-3 text-xs font-bold shadow-md"
        >
          Practice Another Mock Interview →
        </button>
      </div>
    </div>
  );
}
