"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import { useDropzone } from "react-dropzone";
import { AnalysisResult } from "@/types";
import { analyzeResumeText, analyzeResumePDF } from "@/lib/api";
import {
  ATSScoreRing,
  SectionCard,
  LoadingSkeleton,
  AudioInput,
  AudioOutput,
  FaceView,
  InterviewResultsView,
} from "@/components";
import { InterviewEvaluationResult } from "@/components/InterviewResultsView";
import { AudioOutputHandle } from "@/components/AudioOutput";

type AppTab = "enhancer" | "interview";
type InputMode = "text" | "pdf";
type InterviewType = "general" | "hr" | "tr";
type InterviewerTone = "professional" | "friendly" | "strict" | "conversational";

const WS_URL =
  process.env.NEXT_PUBLIC_WS_URL ||
  (typeof window !== "undefined"
    ? `${window.location.protocol === "https:" ? "wss:" : "ws:"}//${window.location.hostname}:8000/ws`
    : "ws://127.0.0.1:8000/ws");

function generateReport(result: AnalysisResult): string {
  const lines: string[] = [
    "RESUME ENHANCEMENT REPORT",
    "Generated by Resumé Edge",
    "=".repeat(50),
    "",
    `ATS SCORE: ${result.ats_score}/100`,
    result.ats_score_explanation,
    "",
    "OVERALL ASSESSMENT",
    "-".repeat(30),
    result.overall_summary,
    "",
    "BOOST YOUR ATS SCORE",
    "-".repeat(30),
    ...(result.ats_improvements || []).map((tip, i) => `[${i + 1}] ${tip}`),
    "",
    "QUICK WINS",
    "-".repeat(30),
    ...result.quick_wins.map((w, i) => `${i + 1}. ${w}`),
    "",
    "MISSING KEYWORDS",
    "-".repeat(30),
    result.keywords_missing.join(", "),
    "",
    "SECTION-BY-SECTION ANALYSIS",
    "=".repeat(50),
  ];

  for (const section of result.sections) {
    lines.push(`\n${section.name.toUpperCase()} [${section.status.replace("_", " ").toUpperCase()}]`);
    lines.push("-".repeat(30));
    if (section.strengths?.length) {
      lines.push("Strengths:");
      section.strengths.forEach((s) => lines.push(`  - ${s}`));
    }
    if (section.improvements?.length) {
      lines.push("Improvements:");
      section.improvements.forEach((s) => lines.push(`  - ${s}`));
    }
    if (section.rewritten_example) {
      lines.push(`Rewrite Example:\n  ${section.rewritten_example}`);
    }
  }

  return lines.join("\n");
}

export default function HomePage() {
  const [activeTab, setActiveTab] = useState<AppTab>("enhancer");

  /* ── Resume Enhancer State ── */
  const [inputMode, setInputMode] = useState<InputMode>("text");
  const [resumeText, setResumeText] = useState("");
  const [jobRole, setJobRole] = useState("");
  const [experienceLevel, setExperienceLevel] = useState("");
  const [pdfFile, setPdfFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [showExtracted, setShowExtracted] = useState(false);

  /* ── AI Avatar Interview State ── */
  const wsRef = useRef<WebSocket | null>(null);
  const [wsStatus, setWsStatus] = useState<string>("disconnected");
  const [isSessionActive, setIsSessionActive] = useState(false);
  const [showInlineUploader, setShowInlineUploader] = useState(false);
  const [interviewType, setInterviewType] = useState<InterviewType>("general");
  const [interviewerTone, setInterviewerTone] = useState<InterviewerTone>("professional");
  const [partialUserText, setPartialUserText] = useState("");
  const [streamingText, setStreamingText] = useState("");
  const [transcript, setTranscript] = useState<
    Array<{ role: string; text: string }>
  >([]);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [interviewEvalResult, setInterviewEvalResult] = useState<InterviewEvaluationResult | null>(null);
  const [evaluatingInterview, setEvaluatingInterview] = useState(false);
  const audioOutputRef = useRef<AudioOutputHandle | null>(null);

  /* ── Dark / Light Theme Mode ── */
  const [theme, setTheme] = useState<"light" | "dark">("light");

  useEffect(() => {
    const savedTheme = (localStorage.getItem("theme") as "light" | "dark") ||
      (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
    setTheme(savedTheme);
    if (savedTheme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, []);

  const toggleTheme = () => {
    const nextTheme = theme === "light" ? "dark" : "light";
    setTheme(nextTheme);
    localStorage.setItem("theme", nextTheme);
    if (nextTheme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  };

  /* ── Cursor-following glow inside Hero Card ── */
  const heroRef = useRef<HTMLDivElement>(null);
  const [glowPos, setGlowPos] = useState({ x: 50, y: 50 });

  useEffect(() => {
    const el = heroRef.current;
    if (!el) return;
    const onMove = (e: MouseEvent) => {
      const rect = el.getBoundingClientRect();
      const x = ((e.clientX - rect.left) / rect.width) * 100;
      const y = ((e.clientY - rect.top) / rect.height) * 100;
      setGlowPos({ x, y });
    };
    el.addEventListener("mousemove", onMove);
    return () => el.removeEventListener("mousemove", onMove);
  }, [activeTab, result, loading]);

  /* ── Canvas cursor trail — Antigravity Particle System ── */
  useEffect(() => {
    const canvas = document.createElement("canvas");
    canvas.style.cssText = "position:fixed;inset:0;pointer-events:none;z-index:9999;";
    document.body.appendChild(canvas);
    const ctx = canvas.getContext("2d")!;
    let w = 0, h = 0;
    const resize = () => { w = canvas.width = window.innerWidth; h = canvas.height = window.innerHeight; };
    resize();
    window.addEventListener("resize", resize);

    let mouseX = w / 2, mouseY = h / 2;
    let smoothX = mouseX, smoothY = mouseY;
    let prevX = mouseX, prevY = mouseY;
    let isMoving = false;
    let moveTimer = 0;

    const onMove = (e: MouseEvent) => {
      mouseX = e.clientX;
      mouseY = e.clientY;
      isMoving = true;
      clearTimeout(moveTimer);
      moveTimer = window.setTimeout(() => { isMoving = false; }, 80);
    };
    document.addEventListener("mousemove", onMove);

    const trail: { x: number; y: number; age: number }[] = [];
    const TRAIL_LENGTH = 20;
    const TRAIL_LIFETIME = 300;

    interface Particle {
      x: number; y: number;
      vx: number; vy: number;
      size: number;
      color: string;
      alpha: number;
      life: number;
      maxLife: number;
      phase: number;
    }
    const particles: Particle[] = [];
    const COLORS = ["#C8F135", "#C8F135", "#111927", "#6b7280"];
    const MAX_PARTICLES = 50;
    let spawnAccum = 0;

    const spawn = (x: number, y: number, speed: number) => {
      if (particles.length >= MAX_PARTICLES) return;
      const angle = Math.random() * Math.PI * 2;
      const force = 0.3 + Math.random() * 0.8;
      particles.push({
        x, y,
        vx: Math.cos(angle) * force + (Math.random() - 0.5) * 0.5,
        vy: -1.2 - Math.random() * 1.5 + Math.sin(angle) * force * 0.5,
        size: 2 + Math.random() * 5,
        color: COLORS[Math.floor(Math.random() * COLORS.length)],
        alpha: 0.6 + Math.random() * 0.3,
        life: 0,
        maxLife: 50 + Math.random() * 40,
        phase: Math.random() * Math.PI * 2,
      });
    };

    let lastFrame = performance.now();
    let animId = 0;

    const loop = (now: number) => {
      animId = requestAnimationFrame(loop);
      const dt = Math.min((now - lastFrame) / 16.667, 3);
      lastFrame = now;
      ctx.clearRect(0, 0, w, h);

      smoothX += (mouseX - smoothX) * 0.15;
      smoothY += (mouseY - smoothY) * 0.15;

      const speed = Math.sqrt((smoothX - prevX) ** 2 + (smoothY - prevY) ** 2);

      if (isMoving && speed > 1.5) {
        spawnAccum += speed * 0.12 * dt;
        while (spawnAccum >= 1) {
          spawnAccum--;
          const t = Math.random();
          const sx = prevX + (smoothX - prevX) * t;
          const sy = prevY + (smoothY - prevY) * t;
          spawn(sx, sy, speed);
        }
      }

      if (isMoving && speed > 0.5) {
        trail.unshift({ x: smoothX, y: smoothY, age: 0 });
      }
      for (let i = trail.length - 1; i >= 0; i--) {
        trail[i].age += 16.667 * dt;
        if (trail[i].age > TRAIL_LIFETIME) { trail.splice(i, 1); continue; }
      }
      if (trail.length > TRAIL_LENGTH) trail.length = TRAIL_LENGTH;

      if (trail.length > 2) {
        ctx.beginPath();
        ctx.moveTo(trail[0].x, trail[0].y);
        for (let i = 1; i < trail.length; i++) {
          const prev = trail[i - 1];
          const curr = trail[i];
          const mx = (prev.x + curr.x) / 2;
          const my = (prev.y + curr.y) / 2;
          ctx.quadraticCurveTo(prev.x, prev.y, mx, my);
        }
        ctx.strokeStyle = "rgba(200, 241, 53, 0.08)";
        ctx.lineWidth = 24;
        ctx.lineCap = "round";
        ctx.stroke();
      }

      const glowAlpha = Math.min(speed * 0.008, 0.12);
      if (glowAlpha > 0.01) {
        const grad = ctx.createRadialGradient(smoothX, smoothY, 0, smoothX, smoothY, 120);
        grad.addColorStop(0, `rgba(200, 241, 53, ${glowAlpha})`);
        grad.addColorStop(0.5, `rgba(200, 241, 53, ${glowAlpha * 0.3})`);
        grad.addColorStop(1, "rgba(200, 241, 53, 0)");
        ctx.fillStyle = grad;
        ctx.fillRect(smoothX - 120, smoothY - 120, 240, 240);
      }

      for (let i = particles.length - 1; i >= 0; i--) {
        const p = particles[i];
        p.life += dt;
        if (p.life >= p.maxLife) { particles.splice(i, 1); continue; }

        const progress = p.life / p.maxLife;
        const ease = 1 - progress;

        p.vy -= 0.02 * dt;
        p.vx += Math.sin(p.life * 0.08 + p.phase) * 0.03 * dt;
        p.vx *= 0.995;
        p.vy *= 0.995;
        p.x += p.vx * dt;
        p.y += p.vy * dt;

        const alpha = p.alpha * ease * ease;
        const scale = 0.3 + ease * 0.7;
        const r = p.size * scale;

        if (alpha < 0.01) continue;

        ctx.globalAlpha = alpha;

        if (p.color === "#C8F135" && r > 2) {
          const glow = ctx.createRadialGradient(p.x, p.y, 0, p.x, p.y, r * 3);
          glow.addColorStop(0, `rgba(200, 241, 53, ${alpha * 0.3})`);
          glow.addColorStop(1, "rgba(200, 241, 53, 0)");
          ctx.fillStyle = glow;
          ctx.fillRect(p.x - r * 3, p.y - r * 3, r * 6, r * 6);
        }

        ctx.beginPath();
        ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
        ctx.fillStyle = p.color;
        ctx.fill();
      }

      ctx.globalAlpha = 1;
      prevX = smoothX;
      prevY = smoothY;
    };

    animId = requestAnimationFrame(loop);

    return () => {
      cancelAnimationFrame(animId);
      document.removeEventListener("mousemove", onMove);
      window.removeEventListener("resize", resize);
      clearTimeout(moveTimer);
      canvas.remove();
    };
  }, []);

  /* ── Resume Dropzone ── */
  const onDrop = useCallback(async (acceptedFiles: File[]) => {
    if (acceptedFiles.length > 0) {
      const file = acceptedFiles[0];
      setPdfFile(file);
      setError(null);
      try {
        const formData = new FormData();
        formData.append("file", file);
        const res = await fetch("http://127.0.0.1:8000/analyze/pdf", {
          method: "POST",
          body: formData,
        });
        if (res.ok) {
          const data = await res.json();
          if (data.extracted_text) {
            setResumeText(data.extracted_text);
          }
        }
      } catch {
        // ignore fallback
      }
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: { "application/pdf": [".pdf"] },
    multiple: false,
  });

  /* ── Springy button micro-interactions ── */
  const springTransition = "transform 0.18s cubic-bezier(0.34, 1.56, 0.64, 1)";
  const springBtn = {
    onMouseEnter: (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(1.04)"; },
    onMouseLeave: (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(1)"; },
    onMouseDown:  (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(0.97)"; },
    onMouseUp:    (e: React.MouseEvent<HTMLElement>) => { e.currentTarget.style.transform = "scale(1.04)"; },
  };

  /* ── Analyze Resume Submit ── */
  const handleAnalyze = async () => {
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      let data: AnalysisResult;
      if (inputMode === "text") {
        if (!resumeText.trim() || resumeText.trim().length < 50) {
          throw new Error("Please paste your resume content (at least 50 characters).");
        }
        data = await analyzeResumeText(resumeText, jobRole, experienceLevel);
      } else {
        if (!pdfFile) throw new Error("Please upload a PDF file.");
        data = await analyzeResumePDF(pdfFile, jobRole, experienceLevel);
        if (data.extracted_text) setResumeText(data.extracted_text);
      }
      setResult(data);
    } catch (err: any) {
      setError(err.message || "Something went wrong.");
    } finally {
      setLoading(false);
    }
  };

  /* ── Context Ref for WebSocket Session Initialization ── */
  const contextRef = useRef({ resumeText, jobRole, interviewType, interviewerTone });
  useEffect(() => {
    contextRef.current = { resumeText, jobRole, interviewType, interviewerTone };
  }, [resumeText, jobRole, interviewType, interviewerTone]);

  /* ── User Barge-In Interruption Callback ── */
  const handleUserBargeIn = useCallback(() => {
    if (isSpeaking) {
      audioOutputRef.current?.stopAll();
      setIsSpeaking(false);
      const socket = wsRef.current;
      if (socket && socket.readyState === WebSocket.OPEN) {
        socket.send(JSON.stringify({ type: "interrupt" }));
      }
    }
  }, [isSpeaking]);

  /* ── WebSocket Connection for AI Avatar Interview ── */
  const connectWebSocket = useCallback(() => {
    if (wsRef.current?.readyState === WebSocket.OPEN) return;

    const socket = new WebSocket(WS_URL);
    wsRef.current = socket;

    socket.onopen = () => {
      setWsStatus("connected");
      const ctx = contextRef.current;
      socket.send(
        JSON.stringify({
          type: "init_session",
          resume_text: ctx.resumeText,
          job_role: ctx.jobRole,
          interview_type: ctx.interviewType,
          interviewer_tone: ctx.interviewerTone,
        })
      );
    };

    socket.onclose = () => {
      setWsStatus("disconnected");
      wsRef.current = null;
    };

    socket.onerror = () => {
      setWsStatus("error");
    };

    socket.onmessage = (ev) => {
      try {
        const msg = JSON.parse(ev.data);
        const type = msg.type;
        const payload = msg.payload ?? "";

        if (type === "status") {
          setWsStatus(payload);
          setIsSpeaking(payload === "speaking");
        } else if (type === "user_text_partial") {
          handleUserBargeIn();
          setPartialUserText(payload);
        } else if (type === "user_text") {
          handleUserBargeIn();
          setPartialUserText("");
          setTranscript((prev) => {
            const last = prev[prev.length - 1];
            if (last && last.role === "user" && last.text === payload) return prev;
            return [...prev, { role: "user", text: payload }];
          });
          setStreamingText("");
        } else if (type === "llm_token") {
          setStreamingText((prev) => prev + payload);
        } else if (type === "assistant_text") {
          setTranscript((prev) => {
            const last = prev[prev.length - 1];
            if (last && last.role === "assistant" && last.text === payload) return prev;
            return [...prev, { role: "assistant", text: payload }];
          });
          setStreamingText("");
        } else if (type === "audio") {
          audioOutputRef.current?.playChunk(payload);
        }
      } catch {
        // ignore
      }
    };
  }, [handleUserBargeIn]);

  /* ── Start / End Interview Session ── */
  const handleToggleInterviewSession = async () => {
    if (isSessionActive) {
      // Stop session
      setIsSessionActive(false);
      audioOutputRef.current?.stopAll();
      setIsSpeaking(false);
      if (wsRef.current) {
        wsRef.current.close();
        wsRef.current = null;
      }
      setWsStatus("disconnected");
    } else {
      // Start session
      setTranscript([]); // Clear previous interview chats
      setStreamingText("");
      setPartialUserText("");
      setActiveTab("interview");
      setIsSessionActive(true);
      audioOutputRef.current?.initContext();
      connectWebSocket();
    }
  };

  const sendAudio = useCallback((base64: string) => {
    const socket = wsRef.current;
    if (!socket || socket.readyState !== WebSocket.OPEN) return;

    if (base64 === "__AUDIO_END__") {
      socket.send(JSON.stringify({ type: "audio_end" }));
    } else {
      socket.send(
        JSON.stringify({
          type: "audio",
          payload: base64,
        })
      );
    }
  }, []);

  const handleGenerateInterviewEvaluation = async () => {
    setEvaluatingInterview(true);
    try {
      const res = await fetch("http://127.0.0.1:8000/interview/evaluate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          transcript,
          job_role: jobRole,
          interview_type: interviewType,
        }),
      });
      if (res.ok) {
        const data = await res.json();
        setInterviewEvalResult(data);
      }
    } catch (err) {
      console.error("Evaluation error:", err);
    } finally {
      setEvaluatingInterview(false);
    }
  };

  const handleStartInterviewFromReport = () => {
    setActiveTab("interview");
    setIsSessionActive(true);
    connectWebSocket();
  };

  const charCount = resumeText.length;
  const charsNeeded = Math.max(0, 50 - charCount);
  const canAnalyze = inputMode === "text" ? charCount >= 50 : !!pdfFile;
  const hasResume = resumeText.trim().length > 0 || pdfFile !== null;

  return (
    <div className="min-h-screen" style={{ fontFamily: "var(--font-body)" }}>
      {/* ── Header ── */}
      <header
        className="border-b sticky top-0 z-50 backdrop-blur-md transition-colors"
        style={{ borderColor: "var(--border)", background: "var(--nav-bg)" }}
      >
        <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span style={{ fontFamily: "var(--font-display)", fontSize: "1.3rem", fontWeight: 700, color: "var(--ink)" }}>
              Resumé Edge
            </span>
          </div>

          <div className="flex items-center gap-3">
            {/* Nav Tabs (Clean Professional Typography) */}
            <div className="tab-group flex rounded-2xl p-1 relative" style={{ background: "var(--paper)", border: "1px solid var(--border)", boxShadow: "0 1px 4px rgba(0,0,0,0.05)" }}>
              <button
                onClick={() => setActiveTab("enhancer")}
                style={{
                  fontFamily: "var(--font-display)",
                  fontWeight: 600,
                  transition: springTransition,
                }}
                {...springBtn}
                className={`px-4 py-2 text-xs font-bold rounded-xl transition-all ${
                  activeTab === "enhancer"
                    ? "bg-[#111927] text-[#C8F135] shadow-md"
                    : "text-gray-600 dark:text-gray-300 hover:text-gray-900"
                }`}
              >
                Resume Enhancer
              </button>
              <button
                onClick={() => setActiveTab("interview")}
                style={{
                  fontFamily: "var(--font-display)",
                  fontWeight: 600,
                  transition: springTransition,
                }}
                {...springBtn}
                className={`px-4 py-2 text-xs font-bold rounded-xl transition-all ${
                  activeTab === "interview"
                    ? "bg-[#111927] text-[#C8F135] shadow-md"
                    : "text-gray-600 dark:text-gray-300 hover:text-gray-900"
                }`}
              >
                AI Interview Avatar
              </button>
            </div>

            {/* Dark / Light Mode Toggle Button */}
            <button
              onClick={toggleTheme}
              title={`Switch to ${theme === "light" ? "Dark" : "Light"} Mode`}
              style={{
                background: "var(--paper)",
                border: "1px solid var(--border)",
                borderRadius: "999px",
                padding: "0.5rem 0.85rem",
                color: "var(--ink)",
                transition: springTransition,
              }}
              {...springBtn}
              className="flex items-center gap-1.5 text-xs font-bold shadow-sm"
            >
              {theme === "light" ? (
                <>
                  <svg className="w-4 h-4 text-amber-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
                  </svg>
                  <span>Light</span>
                </>
              ) : (
                <>
                  <svg className="w-4 h-4 text-sky-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
                  </svg>
                  <span>Dark</span>
                </>
              )}
            </button>

            {/* Reset Button on Header when Result is Active */}
            {activeTab === "enhancer" && result && (
              <button
                onClick={() => setResult(null)}
                className="px-3.5 py-1.5 text-xs font-semibold rounded-xl border border-gray-300 bg-white hover:bg-gray-50 text-gray-700 shadow-sm"
                style={{ transition: springTransition }}
                {...springBtn}
              >
                New Analysis
              </button>
            )}
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-10">
        {/* ══════════════════════════════════════
           TAB 1: RESUME ENHANCER
           ══════════════════════════════════════ */}
        {activeTab === "enhancer" && (
          <div className="space-y-8 animate-fade-in">
            {/* ═══ 1. INPUT FORM VIEW ═══ */}
            {!result && !loading && (
              <>
                {/* Hero Section */}
                <div
                  ref={heroRef}
                  className="hero-bg text-center mb-10 py-16 px-4 rounded-3xl relative"
                  style={{ minHeight: "auto" }}
                >
                  <div
                    style={{
                      position: "absolute",
                      width: 380,
                      height: 380,
                      borderRadius: "50%",
                      background: "rgba(200, 241, 53, 0.15)",
                      top: "-70px",
                      right: "-50px",
                      filter: "blur(100px)",
                      animation: "orbDrift1 18s ease-in-out infinite",
                      pointerEvents: "none",
                      zIndex: 0,
                    }}
                  />
                  <div
                    style={{
                      position: "absolute",
                      width: 300,
                      height: 300,
                      borderRadius: "50%",
                      background: "rgba(17, 25, 39, 0.10)",
                      bottom: "-40px",
                      left: "-30px",
                      filter: "blur(100px)",
                      animation: "orbDrift2 14s ease-in-out infinite",
                      pointerEvents: "none",
                      zIndex: 0,
                    }}
                  />
                  <div
                    style={{
                      position: "absolute",
                      width: 260,
                      height: 260,
                      borderRadius: "50%",
                      background: "rgba(229, 229, 229, 0.20)",
                      top: "30%",
                      left: "55%",
                      filter: "blur(100px)",
                      animation: "orbDrift3 10s ease-in-out infinite",
                      pointerEvents: "none",
                      zIndex: 0,
                    }}
                  />

                  <div
                    style={{
                      position: "absolute",
                      inset: 0,
                      borderRadius: "inherit",
                      background: `radial-gradient(600px circle at ${glowPos.x}% ${glowPos.y}%, rgba(200, 241, 53, 0.35) 0%, transparent 60%)`,
                      pointerEvents: "none",
                      zIndex: 0,
                      transition: "background 0.1s ease-out",
                    }}
                  />

                  <h1
                    className="mb-3 relative"
                    style={{
                      fontFamily: "var(--font-display)",
                      fontSize: "clamp(1.8rem, 6vw, 4rem)",
                      fontWeight: 700,
                      lineHeight: 1.1,
                      color: "var(--ink)",
                      zIndex: 10,
                    }}
                  >
                    <span className="hero-line hero-line--1 block">Make your resume</span>
                    <span className="hero-line hero-line--2 block">
                      <span className="underline-wipe">impossible to ignore.</span>
                    </span>
                  </h1>
                  <p
                    className="hero-line hero-line--3 text-base max-w-md mx-auto relative"
                    style={{ color: "var(--muted)", zIndex: 10 }}
                  >
                    AI-powered analysis covering language, impact, structure, and ATS compatibility.
                  </p>
                </div>

                {/* Marquee Ticker */}
                <div className="marquee-container my-6">
                  <div className="marquee-track">
                    <div className="marquee-pill">
                      <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "0.95rem", color: "var(--ink)", letterSpacing: "0.01em", marginBottom: 4 }}>
                        ATS Score
                      </div>
                      <div style={{ fontSize: "0.7rem", color: "var(--muted)", letterSpacing: "0.04em", textTransform: "uppercase" }}>
                        Compatibility check
                      </div>
                    </div>
                    <div className="marquee-pill">
                      <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "0.95rem", color: "var(--ink)", letterSpacing: "0.01em", marginBottom: 4 }}>
                        Language Fix
                      </div>
                      <div style={{ fontSize: "0.7rem", color: "var(--muted)", letterSpacing: "0.04em", textTransform: "uppercase" }}>
                        Tone &amp; clarity
                      </div>
                    </div>
                    <div className="marquee-pill">
                      <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "0.95rem", color: "var(--ink)", letterSpacing: "0.01em", marginBottom: 4 }}>
                        Quick Wins
                      </div>
                      <div style={{ fontSize: "0.7rem", color: "var(--muted)", letterSpacing: "0.04em", textTransform: "uppercase" }}>
                        Instant improvements
                      </div>
                    </div>
                    <div className="marquee-pill">
                      <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "0.95rem", color: "var(--ink)", letterSpacing: "0.01em", marginBottom: 4 }}>
                        Missing Keywords
                      </div>
                      <div style={{ fontSize: "0.7rem", color: "var(--muted)", letterSpacing: "0.04em", textTransform: "uppercase" }}>
                        Gap analysis
                      </div>
                    </div>
                    <div className="marquee-pill">
                      <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "0.95rem", color: "var(--ink)", letterSpacing: "0.01em", marginBottom: 4 }}>
                        ATS Score
                      </div>
                      <div style={{ fontSize: "0.7rem", color: "var(--muted)", letterSpacing: "0.04em", textTransform: "uppercase" }}>
                        Compatibility check
                      </div>
                    </div>
                    <div className="marquee-pill">
                      <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "0.95rem", color: "var(--ink)", letterSpacing: "0.01em", marginBottom: 4 }}>
                        Language Fix
                      </div>
                      <div style={{ fontSize: "0.7rem", color: "var(--muted)", letterSpacing: "0.04em", textTransform: "uppercase" }}>
                        Tone &amp; clarity
                      </div>
                    </div>
                    <div className="marquee-pill">
                      <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "0.95rem", color: "var(--ink)", letterSpacing: "0.01em", marginBottom: 4 }}>
                        Quick Wins
                      </div>
                      <div style={{ fontSize: "0.7rem", color: "var(--muted)", letterSpacing: "0.04em", textTransform: "uppercase" }}>
                        Instant improvements
                      </div>
                    </div>
                    <div className="marquee-pill">
                      <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "0.95rem", color: "var(--ink)", letterSpacing: "0.01em", marginBottom: 4 }}>
                        Missing Keywords
                      </div>
                      <div style={{ fontSize: "0.7rem", color: "var(--muted)", letterSpacing: "0.04em", textTransform: "uppercase" }}>
                        Gap analysis
                      </div>
                    </div>
                  </div>
                </div>

                {/* Glass Form Card */}
                <div className="glass-card p-6 md:p-8">
                  {/* Tab Group */}
                  <div className="tab-group flex rounded-xl p-1 mb-6 w-fit" style={{ background: "var(--paper)", border: "1px solid var(--border)" }}>
                    <div className="tab-indicator" data-active={inputMode} />
                    <button
                      onClick={() => setInputMode("text")}
                      className={`tab-btn px-4 py-2 rounded-lg text-sm font-medium transition-all ${inputMode === "text" ? "tab-btn--active" : ""}`}
                      style={{ color: inputMode === "text" ? "#0f0f0f" : "var(--ink)", cursor: "pointer" }}
                    >
                      Paste Text
                    </button>
                    <button
                      onClick={() => setInputMode("pdf")}
                      className={`tab-btn px-4 py-2 rounded-lg text-sm font-medium transition-all ${inputMode === "pdf" ? "tab-btn--active" : ""}`}
                      style={{ color: inputMode === "pdf" ? "#0f0f0f" : "var(--ink)", cursor: "pointer" }}
                    >
                      Upload PDF
                    </button>
                  </div>

                  {/* Target Role Input */}
                  <div className="mb-5">
                    <label className="block text-xs font-medium mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                      Target Role / Industry <span style={{ color: "var(--muted)", fontWeight: 400 }}>(optional but recommended)</span>
                    </label>
                    <input
                      type="text"
                      placeholder="e.g. Data Analyst, Software Engineer, Product Manager, Marketing..."
                      value={jobRole}
                      onChange={(e) => setJobRole(e.target.value)}
                      className="input-glow w-full rounded-xl border px-4 py-3 text-sm focus:outline-none"
                      style={{ background: "var(--cream)", borderColor: "var(--border)", color: "var(--ink)", fontFamily: "var(--font-body)" }}
                    />
                  </div>

                  {/* Experience Level Select */}
                  <div className="mb-5">
                    <label className="block text-xs font-medium mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                      Experience Level <span style={{ color: "var(--muted)", fontWeight: 400 }}>(optional but recommended)</span>
                    </label>
                    <select
                      value={experienceLevel}
                      onChange={(e) => setExperienceLevel(e.target.value)}
                      className="input-glow w-full rounded-xl border px-4 py-3 text-sm focus:outline-none"
                      style={{ background: "var(--cream)", borderColor: "var(--border)", color: experienceLevel ? "var(--ink)" : "var(--muted)", fontFamily: "var(--font-body)" }}
                    >
                      <option value="">Select experience level...</option>
                      <option value="student">Student / No Experience</option>
                      <option value="fresher">Fresher (0–1 years)</option>
                      <option value="junior">Junior (1–3 years)</option>
                      <option value="mid">Mid-level (3–6 years)</option>
                      <option value="senior">Senior (6–10 years)</option>
                      <option value="lead">Lead / Principal (10+ years)</option>
                    </select>
                  </div>

                  {/* Input Mode Area */}
                  {inputMode === "text" ? (
                    <div>
                      <label className="block text-xs font-medium mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                        Resume Content
                      </label>
                      <textarea
                        placeholder="Paste your full resume here — work experience, skills, education, summary, everything..."
                        rows={13}
                        value={resumeText}
                        onChange={(e) => setResumeText(e.target.value)}
                        className="input-glow w-full rounded-xl border px-4 py-3 text-sm resize-none focus:outline-none"
                        style={{ background: "var(--cream)", borderColor: "var(--border)", color: "var(--ink)", fontFamily: "var(--font-body)", lineHeight: 1.6 }}
                      />
                      <p className="text-xs mt-1" style={{ color: charCount < 50 ? "var(--muted)" : "var(--green)" }}>
                        {charCount} chars {charsNeeded > 0 ? `(${charsNeeded} more needed)` : "✓ Ready"}
                      </p>
                    </div>
                  ) : (
                    <div>
                      <label className="block text-xs font-bold mb-2 uppercase tracking-widest text-[var(--ink)]">
                        Upload PDF
                      </label>
                      <div
                        {...getRootProps()}
                        className={`border-2 border-dashed border-[#C8F135]/50 rounded-2xl p-10 text-center cursor-pointer transition-all ${
                          isDragActive ? "dropzone-active" : ""
                        }`}
                        style={{ background: "var(--cream)" }}
                      >
                        <input {...getInputProps()} />
                        <div className="w-12 h-12 rounded-full bg-[#C8F135] text-[#111927] flex items-center justify-center mx-auto mb-3 text-sm font-extrabold shadow-[0_0_15px_rgba(200,241,53,0.4)]">
                          PDF
                        </div>
                        {pdfFile ? (
                          <p className="text-sm font-bold text-[var(--ink)]">
                            Selected: {pdfFile.name} ({(pdfFile.size / 1024).toFixed(1)} KB)
                          </p>
                        ) : (
                          <>
                            <p className="text-sm font-bold text-[var(--ink)]">
                              Drag &amp; drop your PDF resume here, or click to browse
                            </p>
                            <p className="text-xs text-[var(--muted)] mt-1 font-medium">Maximum file size: 5MB</p>
                          </>
                        )}
                      </div>
                    </div>
                  )}

                  {error && (
                    <div className="p-4 mt-4 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm">
                      {error}
                    </div>
                  )}

                  {/* CTA Button */}
                  <button
                    onClick={handleAnalyze}
                    disabled={!canAnalyze}
                    className={`btn-cta mt-6 w-full py-4 rounded-xl font-medium ${canAnalyze ? "btn-cta--enabled" : ""}`}
                    style={{
                      background: canAnalyze ? "var(--accent)" : "var(--border)",
                      color: canAnalyze ? "var(--accent-dark)" : "var(--muted)",
                      cursor: canAnalyze ? "pointer" : "not-allowed",
                      fontFamily: "var(--font-display)",
                      fontWeight: 600,
                      fontSize: "1.1rem",
                      transition: springTransition,
                    }}
                    {...(canAnalyze ? springBtn : {})}
                  >
                    {loading ? "Analyzing My Resume..." : "Analyze My Resume →"}
                  </button>
                </div>
              </>
            )}

            {/* ═══ 2. LOADING VIEW ═══ */}
            {loading && (
              <div>
                <div className="text-center mb-8">
                  <h2 style={{ fontFamily: "var(--font-display)", fontSize: "1.8rem", fontWeight: 700 }}>
                    Analyzing your resume...
                  </h2>
                  <p className="text-sm mt-2" style={{ color: "var(--muted)" }}>
                    This takes about 15 seconds. Reading between the lines.
                  </p>
                </div>
                <LoadingSkeleton />
              </div>
            )}

            {/* ═══ 3. RESULTS VIEW (Exact 100% Replica) ═══ */}
            {result && !loading && (
              <div className="animate-fade-in">
                {/* Page Title & Subtitle */}
                <div className="text-center mb-8">
                  <h2 style={{ fontFamily: "var(--font-display)", fontSize: "2rem", fontWeight: 700 }}>
                    Your Analysis is Ready
                  </h2>
                  <p className="text-sm mt-1" style={{ color: "var(--muted)" }}>
                    Here&apos;s what we found — and how to fix it.
                  </p>
                </div>

                {/* 2-Column Grid Layout */}
                <div className="grid md:grid-cols-3 gap-6">
                  {/* Left Column (1/3 width) */}
                  <div className="space-y-5">
                    {/* ATS Score Card */}
                    <div
                      className="p-6 text-center animate-scale-in"
                      style={{
                        background: "#ffffff",
                        border: "1px solid var(--border)",
                        borderRadius: "1.25rem",
                        boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
                      }}
                    >
                      <p
                        className="text-xs font-medium uppercase tracking-widest mb-4"
                        style={{ color: "var(--muted)" }}
                      >
                        ATS Compatibility Score
                      </p>
                      <ATSScoreRing
                        score={result.ats_score}
                        explanation={result.ats_score_explanation}
                      />
                    </div>

                    {/* Boost Your ATS Score Card */}
                    {result.ats_improvements && result.ats_improvements.length > 0 && (
                      <div
                        className="p-5 animate-fade-in"
                        style={{
                          background: "#ffffff",
                          border: "1px solid var(--border)",
                          borderRadius: "1.25rem",
                          boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
                        }}
                      >
                        <p
                          className="text-xs font-medium uppercase tracking-widest mb-3"
                          style={{ color: "var(--green)" }}
                        >
                          BOOST YOUR ATS SCORE
                        </p>
                        <ul className="space-y-2.5">
                          {result.ats_improvements.map((tip, i) => (
                            <li key={i} className="text-sm flex gap-2">
                              <span className="shrink-0 mt-0.5" style={{ color: "var(--green)" }}>
                                ↑
                              </span>
                              <span style={{ color: "var(--muted)" }}>{tip}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Quick Wins Card */}
                    {result.quick_wins && result.quick_wins.length > 0 && (
                      <div
                        className="p-5 animate-fade-in"
                        style={{
                          background: "#ffffff",
                          border: "1px solid var(--border)",
                          borderRadius: "1.25rem",
                          boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
                        }}
                      >
                        <p
                          className="text-xs font-medium uppercase tracking-widest mb-3"
                          style={{ color: "var(--ink)" }}
                        >
                          QUICK WINS
                        </p>
                        <ul className="space-y-2.5">
                          {result.quick_wins.map((win, i) => (
                            <li key={i} className="text-sm flex gap-2">
                              <span className="font-bold mt-0.5 shrink-0" style={{ color: "var(--ink)" }}>
                                {i + 1}.
                              </span>
                              <span style={{ color: "var(--muted)" }}>{win}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Missing Keywords Card */}
                    {result.keywords_missing && result.keywords_missing.length > 0 && (
                      <div
                        className="p-5 animate-fade-in"
                        style={{
                          background: "#ffffff",
                          border: "1px solid var(--border)",
                          borderRadius: "1.25rem",
                          boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
                        }}
                      >
                        <p
                          className="text-xs font-medium uppercase tracking-widest mb-3"
                          style={{ color: "var(--gold)" }}
                        >
                          MISSING KEYWORDS
                        </p>
                        <div className="flex flex-wrap gap-1.5">
                          {result.keywords_missing.map((kw, i) => (
                            <span
                              key={i}
                              className="text-xs px-3 py-1 font-medium"
                              style={{
                                background: "var(--gold-light)",
                                color: "var(--amber)",
                                borderRadius: "999px",
                              }}
                            >
                              {kw}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Right Column (2/3 width) */}
                  <div className="md:col-span-2 space-y-4">
                    {/* Overall Assessment Navy Card */}
                    <div
                      className="p-5 animate-scale-in"
                      style={{
                        background: "var(--ink)",
                        color: "var(--cream)",
                        borderRadius: "1.25rem",
                      }}
                    >
                      <p className="text-xs font-medium uppercase tracking-widest mb-2 opacity-50">
                        Overall Assessment
                      </p>
                      <p className="text-sm leading-relaxed opacity-90">{result.overall_summary}</p>
                    </div>

                    {/* Extracted Text (PDF only) */}
                    {result.extracted_text && (
                      <div
                        className="p-4"
                        style={{
                          background: "#ffffff",
                          border: "1px solid var(--border)",
                          borderRadius: "1.25rem",
                          boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
                        }}
                      >
                        <div className="flex items-center justify-between">
                          <p
                            className="text-xs uppercase tracking-widest font-medium"
                            style={{ color: "var(--muted)" }}
                          >
                            Extracted Text
                          </p>
                          <button
                            onClick={() => setShowExtracted(!showExtracted)}
                            className="text-xs underline underline-offset-2 hover:opacity-80 transition-opacity"
                            style={{ color: "var(--muted)", cursor: "pointer" }}
                          >
                            {showExtracted ? "Hide" : "Show"}
                          </button>
                        </div>
                        {showExtracted && (
                          <pre
                            className="mt-3 text-xs leading-relaxed whitespace-pre-wrap max-h-40 overflow-y-auto"
                            style={{ color: "var(--muted)" }}
                          >
                            {result.extracted_text}
                          </pre>
                        )}
                      </div>
                    )}

                    {/* Section Breakdown Cards */}
                    {result.sections.map((section, i) => (
                      <SectionCard key={section.name || i} section={section} index={i} />
                    ))}
                  </div>
                </div>

                {/* Bottom Actions Row */}
                <div className="flex flex-col sm:flex-row gap-3 justify-center items-center mt-8">
                  <button
                    onClick={() => {
                      const text = generateReport(result);
                      const blob = new Blob([text], { type: "text/plain" });
                      const url = URL.createObjectURL(blob);
                      const a = document.createElement("a");
                      a.href = url;
                      a.download = "Resume_Enhancement_Report.txt";
                      a.click();
                    }}
                    className="px-6 py-3 text-sm font-medium"
                    style={{
                      background: "#ffffff",
                      border: "1px solid var(--border)",
                      borderRadius: "999px",
                      color: "var(--ink)",
                      fontFamily: "var(--font-display)",
                      fontWeight: 600,
                      cursor: "pointer",
                      transition: springTransition,
                    }}
                    {...springBtn}
                  >
                    Download Enhancement Report
                  </button>

                  <button
                    onClick={() => setResult(null)}
                    className="px-6 py-3 text-sm font-medium"
                    style={{
                      background: "var(--accent)",
                      color: "var(--accent-dark)",
                      borderRadius: "999px",
                      fontFamily: "var(--font-display)",
                      fontWeight: 600,
                      border: "none",
                      cursor: "pointer",
                      transition: springTransition,
                    }}
                    {...springBtn}
                  >
                    Analyze Another Resume →
                  </button>

                  <button
                    onClick={handleStartInterviewFromReport}
                    className="px-6 py-3 text-sm font-medium"
                    style={{
                      background: "var(--ink)",
                      color: "var(--accent)",
                      borderRadius: "999px",
                      fontFamily: "var(--font-display)",
                      fontWeight: 600,
                      border: "none",
                      cursor: "pointer",
                      transition: springTransition,
                    }}
                    {...springBtn}
                  >
                    Practice Mock AI Interview →
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* ══════════════════════════════════════
           TAB 2: AI INTERVIEW AVATAR (Clean Professional UI + Spring Button Effects)
           ══════════════════════════════════════ */}
        {activeTab === "interview" && (
          <div className="space-y-8 animate-fade-in">
            {interviewEvalResult ? (
              <InterviewResultsView
                result={interviewEvalResult}
                onRestartSession={() => setInterviewEvalResult(null)}
                jobRole={jobRole}
              />
            ) : (
              <>
                {/* ═══ Hero Section for Interview Avatar ═══ */}
                <div
                  ref={heroRef}
                  className="hero-bg text-center mb-10 py-16 px-4 rounded-3xl relative"
                  style={{ minHeight: "auto" }}
                >
                  <div
                    style={{
                      position: "absolute",
                      width: 380,
                      height: 380,
                      borderRadius: "50%",
                      background: "rgba(200, 241, 53, 0.15)",
                      top: "-70px",
                      right: "-50px",
                      filter: "blur(100px)",
                      animation: "orbDrift1 18s ease-in-out infinite",
                      pointerEvents: "none",
                      zIndex: 0,
                    }}
                  />
                  <div
                    style={{
                      position: "absolute",
                      width: 300,
                      height: 300,
                      borderRadius: "50%",
                      background: "rgba(17, 25, 39, 0.10)",
                      bottom: "-40px",
                      left: "-30px",
                      filter: "blur(100px)",
                      animation: "orbDrift2 14s ease-in-out infinite",
                      pointerEvents: "none",
                      zIndex: 0,
                    }}
                  />
                  <div
                    style={{
                      position: "absolute",
                      width: 260,
                      height: 260,
                      borderRadius: "50%",
                      background: "rgba(229, 229, 229, 0.20)",
                      top: "30%",
                      left: "55%",
                      filter: "blur(100px)",
                      animation: "orbDrift3 10s ease-in-out infinite",
                      pointerEvents: "none",
                      zIndex: 0,
                    }}
                  />

                  <div
                    style={{
                      position: "absolute",
                      inset: 0,
                      borderRadius: "inherit",
                      background: `radial-gradient(600px circle at ${glowPos.x}% ${glowPos.y}%, rgba(200, 241, 53, 0.35) 0%, transparent 60%)`,
                      pointerEvents: "none",
                      zIndex: 0,
                      transition: "background 0.1s ease-out",
                    }}
                  />

                  <h1
                    className="mb-3 relative"
                    style={{
                      fontFamily: "var(--font-display)",
                      fontSize: "clamp(1.8rem, 6vw, 4rem)",
                      fontWeight: 700,
                      lineHeight: 1.1,
                      color: "var(--ink)",
                      zIndex: 10,
                    }}
                  >
                    <span className="hero-line hero-line--1 block">Practice Mock</span>
                    <span className="hero-line hero-line--2 block">
                      <span className="underline-wipe">AI Interviews.</span>
                    </span>
                  </h1>
                  <p
                    className="hero-line hero-line--3 text-base max-w-md mx-auto relative"
                    style={{ color: "var(--muted)", zIndex: 10 }}
                  >
                    Real-time voice evaluation with interactive avatar, hands-free speech streaming, and resume-driven questions.
                  </p>
                </div>

                {/* ═══ Main Glass Card for AI Interviewer ═══ */}
                <div className="glass-card p-6 md:p-10">
                  {/* Header Title Bar */}
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8 pb-6 border-b border-[var(--border)]">
                    <div>
                      <h2 className="text-2xl font-bold text-[var(--ink)]" style={{ fontFamily: "var(--font-display)" }}>
                        AI Interviewer Session
                      </h2>
                      <p className="text-xs text-[var(--muted)] mt-1">
                        Real-time hands-free voice interaction with animated face avatar
                      </p>
                    </div>

                    <div className="flex items-center gap-3 flex-wrap">
                      <button
                        onClick={handleGenerateInterviewEvaluation}
                        disabled={evaluatingInterview}
                        style={{
                          background: "var(--accent)",
                          color: "var(--accent-dark)",
                          fontFamily: "var(--font-display)",
                          fontWeight: 700,
                          fontSize: "0.95rem",
                          transition: springTransition,
                          boxShadow: "0 0 20px rgba(200, 241, 53, 0.4)",
                        }}
                        {...springBtn}
                        className="px-6 py-3 rounded-full flex items-center gap-2.5 shadow-md transition-all disabled:opacity-70"
                      >
                        <span className="w-2.5 h-2.5 rounded-full bg-[#111927]" />
                        {evaluatingInterview ? "Analyzing Interview..." : "Generate Performance Report"}
                      </button>

                      {/* Primary Start / End Session CTA */}
                      <button
                        onClick={handleToggleInterviewSession}
                        style={{
                          background: isSessionActive ? "#dc2626" : "var(--accent)",
                          color: isSessionActive ? "#ffffff" : "var(--accent-dark)",
                          fontFamily: "var(--font-display)",
                          fontWeight: 700,
                          fontSize: "0.95rem",
                          transition: springTransition,
                          boxShadow: isSessionActive
                            ? "0 0 20px rgba(220, 38, 38, 0.4)"
                            : "0 0 20px rgba(200, 241, 53, 0.4)",
                        }}
                        {...springBtn}
                        className="px-6 py-3 rounded-full flex items-center gap-2.5 shadow-md transition-all"
                      >
                        <span className={`w-2.5 h-2.5 rounded-full ${isSessionActive ? "bg-white animate-ping" : "bg-[#111927]"}`} />
                        {isSessionActive ? "End Interview Session" : "Start Interview"}
                      </button>
                    </div>
                  </div>

              {/* ═══ AMBIENT GLASS RESUME & ROLE CONTEXT CARD ═══ */}
              <div
                className="p-8 md:p-9 rounded-3xl mb-8 transition-all duration-300 relative overflow-hidden group shadow-md hover:shadow-xl"
                style={{
                  background: "var(--card-bg)",
                  border: "1px solid rgba(200, 241, 53, 0.4)",
                  boxShadow: "0 8px 30px rgba(0, 0, 0, 0.05), inset 0 1px 0 rgba(255, 255, 255, 0.1)",
                  backdropFilter: "blur(12px)",
                }}
              >
                {/* Background Ambient Radial Glow Effect */}
                <div
                  style={{
                    position: "absolute",
                    top: "-40%",
                    right: "-20%",
                    width: "300px",
                    height: "300px",
                    borderRadius: "50%",
                    background: "radial-gradient(circle, rgba(200, 241, 53, 0.25) 0%, transparent 70%)",
                    pointerEvents: "none",
                  }}
                />

                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4 relative z-10">
                  <div className="flex items-center gap-3 flex-wrap">
                    <span
                      style={{
                        fontFamily: "var(--font-display)",
                        fontSize: "1.1rem",
                        fontWeight: 700,
                        color: "var(--ink)",
                        letterSpacing: "0.01em",
                      }}
                    >
                      Target Role: {jobRole ? jobRole.toUpperCase() : "GENERAL EVALUATION"}
                    </span>
                    <span
                      className={`px-3.5 py-1 rounded-full font-semibold text-xs flex items-center gap-2 ${
                        hasResume
                          ? "bg-[#C8F135]/20 text-[var(--ink)] border border-[#C8F135]/50 shadow-xs"
                          : "bg-amber-50 dark:bg-amber-950/40 text-amber-800 dark:text-amber-300 border border-amber-300 dark:border-amber-700/50"
                      }`}
                    >
                      <span
                        className={`w-2 h-2 rounded-full ${
                          hasResume ? "bg-[#84cc16] animate-pulse" : "bg-amber-500"
                        }`}
                      />
                      {hasResume ? "Resume Attached" : "No Resume Attached"}
                    </span>
                  </div>

                  {/* Upgraded Action Button */}
                  <button
                    onClick={() => setShowInlineUploader(!showInlineUploader)}
                    style={{
                      background: "var(--accent)",
                      color: "var(--accent-dark)",
                      fontFamily: "var(--font-display)",
                      fontWeight: 700,
                      fontSize: "0.85rem",
                      transition: springTransition,
                      boxShadow: "0 0 20px rgba(200, 241, 53, 0.4)",
                    }}
                    {...springBtn}
                    className="px-6 py-2.5 rounded-full flex items-center gap-2 shadow-md transition-all self-start sm:self-auto cursor-pointer"
                  >
                    <span className="w-2 h-2 rounded-full bg-[#111927]" />
                    {showInlineUploader ? "Close Form" : hasResume ? "Edit Resume Context" : "Attach Resume & Role"}
                  </button>
                </div>

                {!showInlineUploader && (
                  <div className="relative z-10 pt-2">
                    {/* Clean Metadata Badges Grid (No Raw PDF Text) */}
                    <div className="flex flex-wrap gap-2.5 items-center">
                      {pdfFile && (
                        <span className="px-3.5 py-1.5 rounded-full bg-[#111927] border border-[#C8F135]/40 text-xs font-semibold text-white shadow-sm flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full bg-[#C8F135] animate-pulse" />
                          File: <span className="text-[#C8F135] font-bold">{pdfFile.name}</span> ({(pdfFile.size / 1024).toFixed(1)} KB)
                        </span>
                      )}

                      {resumeText && !pdfFile && (
                        <span className="px-3.5 py-1.5 rounded-full bg-[#111927] border border-[#C8F135]/40 text-xs font-semibold text-white shadow-sm flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full bg-[#84cc16] animate-pulse" />
                          Text Resume: <span className="text-[#C8F135] font-bold">{resumeText.length} characters</span>
                        </span>
                      )}

                      <span className="px-3.5 py-1.5 rounded-full bg-[#111927] border border-[#C8F135]/40 text-xs font-semibold text-white shadow-sm">
                        Type: <span className="text-[#C8F135] font-bold uppercase">{interviewType}</span>
                      </span>

                      <span className="px-3.5 py-1.5 rounded-full bg-[#111927] border border-[#C8F135]/40 text-xs font-semibold text-white shadow-sm">
                        Tone: <span className="text-[#C8F135] font-bold capitalize">{interviewerTone}</span>
                      </span>
                    </div>
                  </div>
                )}

                {/* Inline Resume & Context Input Form (Spacious HR/TR & Tone Controls) */}
                {showInlineUploader && (
                  <div className="mt-6 pt-6 border-t border-gray-200 space-y-6 animate-fade-in">
                    {/* Tab Group: Paste Text vs Upload PDF */}
                    <div className="tab-group flex rounded-xl p-1 w-fit" style={{ background: "var(--paper)", border: "1px solid var(--border)" }}>
                      <div className="tab-indicator" data-active={inputMode} />
                      <button
                        onClick={() => setInputMode("text")}
                        className={`tab-btn px-5 py-2 rounded-lg text-xs font-semibold transition-all ${inputMode === "text" ? "tab-btn--active" : ""}`}
                        style={{ color: inputMode === "text" ? "var(--accent-dark)" : "var(--muted)", cursor: "pointer" }}
                      >
                        Paste Text
                      </button>
                      <button
                        onClick={() => setInputMode("pdf")}
                        className={`tab-btn px-5 py-2 rounded-lg text-xs font-semibold transition-all ${inputMode === "pdf" ? "tab-btn--active" : ""}`}
                        style={{ color: inputMode === "pdf" ? "var(--accent-dark)" : "var(--muted)", cursor: "pointer" }}
                      >
                        Upload PDF
                      </button>
                    </div>

                    {/* Interview Type (HR / TR / General) & Tone Selectors */}
                    <div className="grid md:grid-cols-2 gap-5">
                      <div>
                        <label className="block text-xs font-semibold mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                          Interview Type (HR / TR)
                        </label>
                        <select
                          value={interviewType}
                          onChange={(e) => setInterviewType(e.target.value as InterviewType)}
                          className="input-glow w-full rounded-xl border px-4 py-3.5 text-sm focus:outline-none"
                          style={{ background: "var(--cream)", borderColor: "var(--border)", color: "var(--ink)", fontFamily: "var(--font-body)" }}
                        >
                          <option value="general">General / Mixed Hiring Interview</option>
                          <option value="hr">HR / Behavioral Interview (STAR Method)</option>
                          <option value="tr">TR / Technical Interview (Coding &amp; Architecture)</option>
                        </select>
                      </div>

                      <div>
                        <label className="block text-xs font-semibold mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                          Interviewer Tone
                        </label>
                        <select
                          value={interviewerTone}
                          onChange={(e) => setInterviewerTone(e.target.value as InterviewerTone)}
                          className="input-glow w-full rounded-xl border px-4 py-3.5 text-sm focus:outline-none"
                          style={{ background: "var(--cream)", borderColor: "var(--border)", color: "var(--ink)", fontFamily: "var(--font-body)" }}
                        >
                          <option value="professional">Professional &amp; Formal</option>
                          <option value="friendly">Friendly &amp; Encouraging</option>
                          <option value="strict">Strict &amp; Challenging (Pressure Test)</option>
                          <option value="conversational">Conversational &amp; Casual</option>
                        </select>
                      </div>
                    </div>

                    {/* Target Role Input */}
                    <div>
                      <label className="block text-xs font-semibold mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                        Target Role / Industry <span style={{ color: "var(--muted)", fontWeight: 400 }}>(optional but recommended)</span>
                      </label>
                      <input
                        type="text"
                        placeholder="e.g. Data Analyst, Software Engineer, Product Manager, Marketing..."
                        value={jobRole}
                        onChange={(e) => setJobRole(e.target.value)}
                        className="input-glow w-full rounded-xl border px-4 py-3.5 text-sm focus:outline-none"
                        style={{ background: "var(--cream)", borderColor: "var(--border)", color: "var(--ink)", fontFamily: "var(--font-body)" }}
                      />
                    </div>

                    {/* Experience Level Select */}
                    <div>
                      <label className="block text-xs font-semibold mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                        Experience Level <span style={{ color: "var(--muted)", fontWeight: 400 }}>(optional but recommended)</span>
                      </label>
                      <select
                        value={experienceLevel}
                        onChange={(e) => setExperienceLevel(e.target.value)}
                        className="input-glow w-full rounded-xl border px-4 py-3.5 text-sm focus:outline-none"
                        style={{ background: "var(--cream)", borderColor: "var(--border)", color: experienceLevel ? "var(--ink)" : "var(--muted)", fontFamily: "var(--font-body)" }}
                      >
                        <option value="">Select experience level...</option>
                        <option value="student">Student / No Experience</option>
                        <option value="fresher">Fresher (0–1 years)</option>
                        <option value="junior">Junior (1–3 years)</option>
                        <option value="mid">Mid-level (3–6 years)</option>
                        <option value="senior">Senior (6–10 years)</option>
                        <option value="lead">Lead / Principal (10+ years)</option>
                      </select>
                    </div>

                    {/* Input Mode Area */}
                    {inputMode === "text" ? (
                      <div>
                        <label className="block text-xs font-semibold mb-2 uppercase tracking-widest" style={{ color: "var(--muted)" }}>
                          Resume Content
                        </label>
                        <textarea
                          placeholder="Paste your full resume here — work experience, skills, education, summary, everything..."
                          rows={8}
                          value={resumeText}
                          onChange={(e) => setResumeText(e.target.value)}
                          className="input-glow w-full rounded-xl border px-4 py-3.5 text-sm resize-none focus:outline-none"
                          style={{ background: "var(--cream)", borderColor: "var(--border)", color: "var(--ink)", fontFamily: "var(--font-body)", lineHeight: 1.6 }}
                        />
                        <p className="text-xs mt-1.5 font-medium" style={{ color: charCount < 50 ? "var(--muted)" : "var(--green)" }}>
                          {charCount} chars {charsNeeded > 0 ? `(${charsNeeded} more needed)` : "✓ Ready"}
                        </p>
                      </div>
                    ) : (
                      <div>
                        <label className="block text-xs font-bold mb-2 uppercase tracking-widest text-[var(--ink)]">
                          Upload PDF
                        </label>
                        <div
                          {...getRootProps()}
                          className={`border-2 border-dashed border-[#C8F135]/50 rounded-2xl p-8 text-center cursor-pointer transition-all ${
                            isDragActive ? "dropzone-active" : ""
                          }`}
                          style={{ background: "var(--cream)" }}
                        >
                          <input {...getInputProps()} />
                          <div className="w-12 h-12 rounded-full bg-[#C8F135] text-[#111927] flex items-center justify-center mx-auto mb-3 text-sm font-extrabold shadow-[0_0_15px_rgba(200,241,53,0.4)]">
                            PDF
                          </div>
                          {pdfFile ? (
                            <p className="text-sm font-bold text-[var(--ink)]">
                              Selected: {pdfFile.name} ({(pdfFile.size / 1024).toFixed(1)} KB)
                            </p>
                          ) : (
                            <>
                              <p className="text-sm font-bold text-[var(--ink)]">
                                Drag &amp; drop your PDF resume here, or click to browse
                              </p>
                              <p className="text-xs text-[var(--muted)] mt-1 font-medium">Maximum file size: 5MB</p>
                            </>
                          )}
                        </div>
                      </div>
                    )}

                    <div className="flex gap-3 justify-end pt-2">
                      <button
                        onClick={() => setShowInlineUploader(false)}
                        style={{
                          background: "var(--accent)",
                          color: "var(--accent-dark)",
                          fontFamily: "var(--font-display)",
                          fontWeight: 700,
                          fontSize: "0.85rem",
                          transition: springTransition,
                          boxShadow: "0 0 20px rgba(200, 241, 53, 0.4)",
                        }}
                        {...springBtn}
                        className="px-6 py-2.5 rounded-full shadow-md transition-all cursor-pointer"
                      >
                        Save Context
                      </button>
                    </div>
                  </div>
                )}
              </div>

              {/* Face View Canvas */}
              <div className="mb-6">
                <FaceView isSpeaking={isSpeaking} wsStatus={wsStatus} />
              </div>

              {/* Hands-Free Mic Active Indicator */}
              <div className="flex justify-center mb-8">
                <AudioInput
                  onAudioChunk={sendAudio}
                  onUserBargeIn={handleUserBargeIn}
                  isSessionActive={isSessionActive}
                  wsStatus={wsStatus}
                  isAiSpeaking={isSpeaking}
                  disabled={!isSessionActive}
                />
              </div>

              {/* Live Transcript Chat Header & Clear Action */}
              <div className="flex items-center justify-between mb-3 px-1">
                <span className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">
                  Live Interview Transcript
                </span>
                {transcript.length > 0 && (
                  <button
                    onClick={() => setTranscript([])}
                    style={{
                      fontFamily: "var(--font-display)",
                      fontWeight: 600,
                      transition: springTransition,
                    }}
                    {...springBtn}
                    className="px-3.5 py-1 rounded-full text-xs font-semibold bg-red-500/10 text-red-600 dark:text-red-400 border border-red-500/30 hover:bg-red-500 hover:text-white transition-all shadow-xs cursor-pointer"
                  >
                    Clear Chat
                  </button>
                )}
              </div>

              <div className="rounded-2xl border border-[var(--border)] bg-[var(--paper)] p-5 max-h-80 overflow-y-auto space-y-3">
                {!isSessionActive && transcript.length === 0 && (
                  <p className="text-center text-xs text-[var(--muted)] py-6">
                    Click <strong>"Start Interview"</strong> to begin your AI mock interview session.
                  </p>
                )}

                {transcript.map((m, i) => (
                  <div
                    key={i}
                    className={`p-4 rounded-2xl text-sm transition-all ${
                      m.role === "user"
                        ? "bg-[#111927] text-white ml-auto max-w-[80%] shadow-sm"
                        : "bg-[var(--cream)] text-[var(--ink)] border border-[var(--border)] mr-auto max-w-[80%] shadow-sm"
                    }`}
                  >
                    <span className={`text-xs font-bold block mb-1 ${m.role === "user" ? "text-[#C8F135]" : "text-[var(--muted)]"}`}>
                      {m.role === "user" ? "You" : "AI Interviewer"}
                    </span>
                    {m.text}
                  </div>
                ))}

                {/* Live partial speech feedback */}
                {partialUserText && (
                  <div className="p-4 rounded-2xl text-sm bg-[#111927] text-[#C8F135] ml-auto max-w-[80%] border border-[#C8F135]/40 shadow-md animate-pulse">
                    <span className="text-xs font-bold block mb-1 text-[#C8F135]">
                      You (speaking...)
                    </span>
                    {partialUserText} ...
                  </div>
                )}

                {/* Streaming Assistant Tokens */}
                {streamingText && (
                  <div className="p-4 rounded-2xl text-sm bg-[var(--cream)] text-[var(--ink)] border border-[var(--border)] mr-auto max-w-[80%] shadow-sm">
                    <span className="text-xs font-bold block mb-1 text-[var(--muted)]">
                      AI Interviewer (thinking...)
                    </span>
                    {streamingText}
                  </div>
                )}
              </div>

              <AudioOutput ref={audioOutputRef} onSpeakingChange={(speaking) => setIsSpeaking(speaking)} />
            </div>
          </>
        )}
      </div>
    )}
      </main>

      {/* Footer */}
      <footer className="mt-16 border-t py-6 text-center" style={{ borderColor: "var(--border)" }}>
        <p className="text-xs" style={{ color: "var(--muted)" }}>
          Resumé Edge · Your data is never stored
        </p>
      </footer>
    </div>
  );
}
